// Code generated by generate/sdk; DO NOT EDIT.

package sdk

import (
	"github.com/dokku/docket/internal/subprocess"
	"github.com/dokku/docket/internal/tasks"
)

// AclAppTask is tasks.AclAppTask.
type AclAppTask = tasks.AclAppTask

// AclServiceTask is tasks.AclServiceTask.
type AclServiceTask = tasks.AclServiceTask

// AppCloneTask is tasks.AppCloneTask.
type AppCloneTask = tasks.AppCloneTask

// AppJsonPropertyTask is tasks.AppJsonPropertyTask.
type AppJsonPropertyTask = tasks.AppJsonPropertyTask

// AppLockTask is tasks.AppLockTask.
type AppLockTask = tasks.AppLockTask

// AppTask is tasks.AppTask.
type AppTask = tasks.AppTask

// AppsPropertyTask is tasks.AppsPropertyTask.
type AppsPropertyTask = tasks.AppsPropertyTask

// BuilderDockerfilePropertyTask is tasks.BuilderDockerfilePropertyTask.
type BuilderDockerfilePropertyTask = tasks.BuilderDockerfilePropertyTask

// BuilderHerokuishPropertyTask is tasks.BuilderHerokuishPropertyTask.
type BuilderHerokuishPropertyTask = tasks.BuilderHerokuishPropertyTask

// BuilderLambdaPropertyTask is tasks.BuilderLambdaPropertyTask.
type BuilderLambdaPropertyTask = tasks.BuilderLambdaPropertyTask

// BuilderNixpacksPropertyTask is tasks.BuilderNixpacksPropertyTask.
type BuilderNixpacksPropertyTask = tasks.BuilderNixpacksPropertyTask

// BuilderPackPropertyTask is tasks.BuilderPackPropertyTask.
type BuilderPackPropertyTask = tasks.BuilderPackPropertyTask

// BuilderPropertyTask is tasks.BuilderPropertyTask.
type BuilderPropertyTask = tasks.BuilderPropertyTask

// BuilderRailpackPropertyTask is tasks.BuilderRailpackPropertyTask.
type BuilderRailpackPropertyTask = tasks.BuilderRailpackPropertyTask

// BuildpacksPropertyTask is tasks.BuildpacksPropertyTask.
type BuildpacksPropertyTask = tasks.BuildpacksPropertyTask

// BuildpacksTask is tasks.BuildpacksTask.
type BuildpacksTask = tasks.BuildpacksTask

// BuildsPropertyTask is tasks.BuildsPropertyTask.
type BuildsPropertyTask = tasks.BuildsPropertyTask

// CaddyPropertyTask is tasks.CaddyPropertyTask.
type CaddyPropertyTask = tasks.CaddyPropertyTask

// CertsTask is tasks.CertsTask.
type CertsTask = tasks.CertsTask

// ChecksPropertyTask is tasks.ChecksPropertyTask.
type ChecksPropertyTask = tasks.ChecksPropertyTask

// ChecksToggleTask is tasks.ChecksToggleTask.
type ChecksToggleTask = tasks.ChecksToggleTask

// ConfigTask is tasks.ConfigTask.
type ConfigTask = tasks.ConfigTask

// CronPropertyTask is tasks.CronPropertyTask.
type CronPropertyTask = tasks.CronPropertyTask

// DockerOptionsTask is tasks.DockerOptionsTask.
type DockerOptionsTask = tasks.DockerOptionsTask

// DomainsTask is tasks.DomainsTask.
type DomainsTask = tasks.DomainsTask

// DomainsToggleTask is tasks.DomainsToggleTask.
type DomainsToggleTask = tasks.DomainsToggleTask

// DynamicPropertySchema is tasks.DynamicPropertySchema.
type DynamicPropertySchema = tasks.DynamicPropertySchema

// ExampleSchema is tasks.ExampleSchema.
type ExampleSchema = tasks.ExampleSchema

// ExportOptions is tasks.ExportOptions.
type ExportOptions = tasks.ExportOptions

// ExportReport is tasks.ExportReport.
type ExportReport = tasks.ExportReport

// ExportResult is tasks.ExportResult.
type ExportResult = tasks.ExportResult

// ExportStatus is tasks.ExportStatus.
type ExportStatus = tasks.ExportStatus

// ExportSupport is tasks.ExportSupport.
type ExportSupport = tasks.ExportSupport

// ExportedPlay is tasks.ExportedPlay.
type ExportedPlay = tasks.ExportedPlay

// ExportedTask is tasks.ExportedTask.
type ExportedTask = tasks.ExportedTask

// FieldSchema is tasks.FieldSchema.
type FieldSchema = tasks.FieldSchema

// GitAuthTask is tasks.GitAuthTask.
type GitAuthTask = tasks.GitAuthTask

// GitFromArchiveTask is tasks.GitFromArchiveTask.
type GitFromArchiveTask = tasks.GitFromArchiveTask

// GitFromImageTask is tasks.GitFromImageTask.
type GitFromImageTask = tasks.GitFromImageTask

// GitPropertyTask is tasks.GitPropertyTask.
type GitPropertyTask = tasks.GitPropertyTask

// GitSyncTask is tasks.GitSyncTask.
type GitSyncTask = tasks.GitSyncTask

// HaproxyPropertyTask is tasks.HaproxyPropertyTask.
type HaproxyPropertyTask = tasks.HaproxyPropertyTask

// HttpAuthAllowedIpTask is tasks.HttpAuthAllowedIpTask.
type HttpAuthAllowedIpTask = tasks.HttpAuthAllowedIpTask

// HttpAuthDomainTask is tasks.HttpAuthDomainTask.
type HttpAuthDomainTask = tasks.HttpAuthDomainTask

// HttpAuthTask is tasks.HttpAuthTask.
type HttpAuthTask = tasks.HttpAuthTask

// HttpAuthUser is tasks.HttpAuthUser.
type HttpAuthUser = tasks.HttpAuthUser

// HttpAuthUserTask is tasks.HttpAuthUserTask.
type HttpAuthUserTask = tasks.HttpAuthUserTask

// IdentityCollectionSchema is tasks.IdentityCollectionSchema.
type IdentityCollectionSchema = tasks.IdentityCollectionSchema

// IdentitySchema is tasks.IdentitySchema.
type IdentitySchema = tasks.IdentitySchema

// ItemIdentity is tasks.ItemIdentity.
type ItemIdentity = tasks.ItemIdentity

// ItemSchema is tasks.ItemSchema.
type ItemSchema = tasks.ItemSchema

// LetsencryptPropertyTask is tasks.LetsencryptPropertyTask.
type LetsencryptPropertyTask = tasks.LetsencryptPropertyTask

// LetsencryptTask is tasks.LetsencryptTask.
type LetsencryptTask = tasks.LetsencryptTask

// LogsPropertyTask is tasks.LogsPropertyTask.
type LogsPropertyTask = tasks.LogsPropertyTask

// MaintenanceCustomPageTask is tasks.MaintenanceCustomPageTask.
type MaintenanceCustomPageTask = tasks.MaintenanceCustomPageTask

// MaintenanceTask is tasks.MaintenanceTask.
type MaintenanceTask = tasks.MaintenanceTask

// Masker is subprocess.Masker.
type Masker = subprocess.Masker

// NetworkPropertyTask is tasks.NetworkPropertyTask.
type NetworkPropertyTask = tasks.NetworkPropertyTask

// NetworkTask is tasks.NetworkTask.
type NetworkTask = tasks.NetworkTask

// NginxPropertyTask is tasks.NginxPropertyTask.
type NginxPropertyTask = tasks.NginxPropertyTask

// OpenrestyPropertyTask is tasks.OpenrestyPropertyTask.
type OpenrestyPropertyTask = tasks.OpenrestyPropertyTask

// PlanResult is tasks.PlanResult.
type PlanResult = tasks.PlanResult

// PlanStatus is tasks.PlanStatus.
type PlanStatus = tasks.PlanStatus

// PlanWarning is tasks.PlanWarning.
type PlanWarning = tasks.PlanWarning

// PluginTask is tasks.PluginTask.
type PluginTask = tasks.PluginTask

// PortMapping is tasks.PortMapping.
type PortMapping = tasks.PortMapping

// PortsTask is tasks.PortsTask.
type PortsTask = tasks.PortsTask

// ProbeStatus is tasks.ProbeStatus.
type ProbeStatus = tasks.ProbeStatus

// ProbeSupport is tasks.ProbeSupport.
type ProbeSupport = tasks.ProbeSupport

// PropertyEntrySchema is tasks.PropertyEntrySchema.
type PropertyEntrySchema = tasks.PropertyEntrySchema

// PropertySchema is tasks.PropertySchema.
type PropertySchema = tasks.PropertySchema

// ProxyPropertyTask is tasks.ProxyPropertyTask.
type ProxyPropertyTask = tasks.ProxyPropertyTask

// ProxyToggleTask is tasks.ProxyToggleTask.
type ProxyToggleTask = tasks.ProxyToggleTask

// PsPropertyTask is tasks.PsPropertyTask.
type PsPropertyTask = tasks.PsPropertyTask

// PsScaleTask is tasks.PsScaleTask.
type PsScaleTask = tasks.PsScaleTask

// RegistryAuthTask is tasks.RegistryAuthTask.
type RegistryAuthTask = tasks.RegistryAuthTask

// RegistryPropertyTask is tasks.RegistryPropertyTask.
type RegistryPropertyTask = tasks.RegistryPropertyTask

// RejectedPropertySchema is tasks.RejectedPropertySchema.
type RejectedPropertySchema = tasks.RejectedPropertySchema

// ResourceLimitTask is tasks.ResourceLimitTask.
type ResourceLimitTask = tasks.ResourceLimitTask

// ResourceReserveTask is tasks.ResourceReserveTask.
type ResourceReserveTask = tasks.ResourceReserveTask

// ResourceSelector is tasks.ResourceSelector.
type ResourceSelector = tasks.ResourceSelector

// SchedulerDockerLocalPropertyTask is tasks.SchedulerDockerLocalPropertyTask.
type SchedulerDockerLocalPropertyTask = tasks.SchedulerDockerLocalPropertyTask

// SchedulerK3sAnnotationsTask is tasks.SchedulerK3sAnnotationsTask.
type SchedulerK3sAnnotationsTask = tasks.SchedulerK3sAnnotationsTask

// SchedulerK3sAutoscalingAuthTask is tasks.SchedulerK3sAutoscalingAuthTask.
type SchedulerK3sAutoscalingAuthTask = tasks.SchedulerK3sAutoscalingAuthTask

// SchedulerK3sChartTask is tasks.SchedulerK3sChartTask.
type SchedulerK3sChartTask = tasks.SchedulerK3sChartTask

// SchedulerK3sLabelsTask is tasks.SchedulerK3sLabelsTask.
type SchedulerK3sLabelsTask = tasks.SchedulerK3sLabelsTask

// SchedulerK3sNodeSysctlsTask is tasks.SchedulerK3sNodeSysctlsTask.
type SchedulerK3sNodeSysctlsTask = tasks.SchedulerK3sNodeSysctlsTask

// SchedulerK3sProfileTask is tasks.SchedulerK3sProfileTask.
type SchedulerK3sProfileTask = tasks.SchedulerK3sProfileTask

// SchedulerK3sPropertyTask is tasks.SchedulerK3sPropertyTask.
type SchedulerK3sPropertyTask = tasks.SchedulerK3sPropertyTask

// SchedulerPropertyTask is tasks.SchedulerPropertyTask.
type SchedulerPropertyTask = tasks.SchedulerPropertyTask

// ServiceBackupTask is tasks.ServiceBackupTask.
type ServiceBackupTask = tasks.ServiceBackupTask

// ServiceCreateTask is tasks.ServiceCreateTask.
type ServiceCreateTask = tasks.ServiceCreateTask

// ServiceExposeTask is tasks.ServiceExposeTask.
type ServiceExposeTask = tasks.ServiceExposeTask

// ServiceLinkTask is tasks.ServiceLinkTask.
type ServiceLinkTask = tasks.ServiceLinkTask

// ServicePropertyTask is tasks.ServicePropertyTask.
type ServicePropertyTask = tasks.ServicePropertyTask

// Session is subprocess.Session.
type Session = subprocess.Session

// SshKeyTask is tasks.SshKeyTask.
type SshKeyTask = tasks.SshKeyTask

// State is tasks.State.
type State = tasks.State

// StorageEnsureTask is tasks.StorageEnsureTask.
type StorageEnsureTask = tasks.StorageEnsureTask

// StorageEntryTask is tasks.StorageEntryTask.
type StorageEntryTask = tasks.StorageEntryTask

// StorageMount is tasks.StorageMount.
type StorageMount = tasks.StorageMount

// StorageMountTask is tasks.StorageMountTask.
type StorageMountTask = tasks.StorageMountTask

// Target is subprocess.Target.
type Target = subprocess.Target

// Task is tasks.Task.
type Task = tasks.Task

// TaskCatalog is tasks.TaskCatalog.
type TaskCatalog = tasks.TaskCatalog

// TaskOutputState is tasks.TaskOutputState.
type TaskOutputState = tasks.TaskOutputState

// TaskSchema is tasks.TaskSchema.
type TaskSchema = tasks.TaskSchema

// TraefikPropertyTask is tasks.TraefikPropertyTask.
type TraefikPropertyTask = tasks.TraefikPropertyTask
