// Command sdk writes sdk/types_gen.go: a type alias in the public sdk package
// for every engine type an embedding caller has to be able to name.
//
// The engine lives under internal/, so a caller outside this module cannot
// import it. The sdk package re-exports the embedding surface, and the types in
// that surface are aliases rather than copies so a value built through sdk is
// the engine's own value. Which types that is follows from the surface itself:
// every registered task, plus the API's own result and option types, plus
// every named engine type reachable through their exported fields. Writing
// that list by hand would miss the next task someone adds, so it is derived
// here by reflection and TestGeneratedSDKIsCurrent fails when the committed
// file falls behind.
//
// It is run by `go generate` from the sdk directory, which is where the output
// is written.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"reflect"
	"sort"

	"github.com/dokku/docket/internal/subprocess"
	"github.com/dokku/docket/internal/tasks"
)

// outputFile is the generated file's name, relative to the sdk directory.
const outputFile = "types_gen.go"

// aliasedPackages maps each engine package whose types are aliased to the
// name the generated file imports it under.
var aliasedPackages = map[string]string{
	reflect.TypeOf(tasks.TaskCatalog{}).PkgPath(): "tasks",
	reflect.TypeOf(subprocess.Target{}).PkgPath(): "subprocess",
}

// roots are the sdk surface's own types. Every registered task is added to
// these at render time.
var roots = []reflect.Type{
	reflect.TypeOf((*tasks.Task)(nil)).Elem(),
	reflect.TypeOf(tasks.ExportOptions{}),
	reflect.TypeOf(tasks.ExportResult{}),
	reflect.TypeOf(tasks.ExportReport{}),
	reflect.TypeOf(tasks.ExportedPlay{}),
	reflect.TypeOf(tasks.ExportedTask{}),
	reflect.TypeOf(tasks.ResourceSelector{}),
	reflect.TypeOf(tasks.TaskCatalog{}),
	reflect.TypeOf(tasks.PlanResult{}),
	reflect.TypeOf(tasks.TaskOutputState{}),
	reflect.TypeOf(tasks.ProbeSupport{}),
	reflect.TypeOf(tasks.ExportSupport{}),
	reflect.TypeOf(subprocess.Session{}),
	reflect.TypeOf(subprocess.Target{}),
	reflect.TypeOf(subprocess.Masker{}),
}

// collect walks t and records every exported named type from an aliased
// package that it is, or reaches through exported struct fields and
// pointer, slice, array and map elements.
func collect(t reflect.Type, seen map[reflect.Type]bool) {
	switch t.Kind() {
	case reflect.Pointer, reflect.Slice, reflect.Array:
		collect(t.Elem(), seen)
		return
	case reflect.Map:
		collect(t.Key(), seen)
		collect(t.Elem(), seen)
		return
	}

	if seen[t] {
		return
	}
	if _, ok := aliasedPackages[t.PkgPath()]; !ok || !isExported(t.Name()) {
		return
	}
	seen[t] = true

	if t.Kind() != reflect.Struct {
		return
	}
	for i := 0; i < t.NumField(); i++ {
		if field := t.Field(i); field.IsExported() {
			collect(field.Type, seen)
		}
	}
}

func isExported(name string) bool {
	return name != "" && name[0] >= 'A' && name[0] <= 'Z'
}

// render returns the formatted contents of sdk/types_gen.go.
func render() ([]byte, error) {
	seen := map[reflect.Type]bool{}
	for _, root := range roots {
		collect(root, seen)
	}
	for _, typeKey := range tasks.TaskTypes() {
		task, ok := tasks.Lookup(typeKey)
		if !ok {
			return nil, fmt.Errorf("task type %q is listed but not registered", typeKey)
		}
		collect(reflect.TypeOf(task), seen)
	}

	names := map[string]reflect.Type{}
	for t := range seen {
		if other, ok := names[t.Name()]; ok {
			return nil, fmt.Errorf("type name %s is declared in both %s and %s", t.Name(), other.PkgPath(), t.PkgPath())
		}
		names[t.Name()] = t
	}
	sorted := make([]string, 0, len(names))
	for name := range names {
		sorted = append(sorted, name)
	}
	sort.Strings(sorted)

	importPaths := make([]string, 0, len(aliasedPackages))
	for importPath := range aliasedPackages {
		importPaths = append(importPaths, importPath)
	}
	sort.Strings(importPaths)

	var buf bytes.Buffer
	buf.WriteString("// Code generated by generate/sdk; DO NOT EDIT.\n\n")
	buf.WriteString("package sdk\n\n")
	buf.WriteString("import (\n")
	for _, importPath := range importPaths {
		fmt.Fprintf(&buf, "\t%q\n", importPath)
	}
	buf.WriteString(")\n\n")
	for _, name := range sorted {
		qualified := aliasedPackages[names[name].PkgPath()] + "." + name
		fmt.Fprintf(&buf, "// %s is %s.\n", name, qualified)
		fmt.Fprintf(&buf, "type %s = %s\n\n", name, qualified)
	}

	return format.Source(buf.Bytes())
}

func main() {
	source, err := render()
	if err != nil {
		log.Fatalf("failed to render %s: %v", outputFile, err)
	}
	if err := os.WriteFile(outputFile, source, 0644); err != nil {
		log.Fatalf("failed to write %s: %v", outputFile, err)
	}
}
